import { P, C, src } from './_lib.mjs';

// ITI trades share one regulated pipeline (DGT/NCVT): admission -> trade training -> AITT/NTC -> apprenticeship -> jobs/upgrade.
const iti = ({ slug, name, title, dur, elig, learn, tools, safety, apprentice, jobs, selfEmp, upgrade, licence }) => C(slug, name, title,
  `The ITI ${name.replace(/^ITI /, '')} roadmap: eligibility, admission, trade training, the All India Trade Test, apprenticeship and jobs, in order.`,
  [['Duration', dur], ['Eligibility', elig], ['Regulator', 'DGT / NCVT'], ['Certificate', 'NCVT National Trade Certificate (NTC)']],
  [
    P('Eligibility after Class 8 or 10', 'After Class 8 / 10', `Eligibility for this trade: ${elig}.`, [
      'ITI admission needs a minimum age of 14 years and the Class 8 or Class 10 pass level fixed for the trade; check the exact requirement on your state’s ITI admission portal.',
      'Science and Maths in school help for technical trades, but you can still join if the trade allows it.',
      'Choose the trade by interest and local job demand; talk to ITI instructors and working technicians.',
      'Government ITIs have limited seats and low fees; private ITIs must be affiliated to NCVT, so verify affiliation on the DGT site.'],
      [['Eligibility', elig], ['Min. age', '14 years'], ['Check', 'NCVT affiliation of the ITI']]),
    P('ITI admission process', 'Admission window (usually June–August)', 'Online application on the state ITI portal, merit list and counselling.', [
      'Register on your state’s ITI admission portal (or the DGT portal where used), enter marks, upload documents and pay the application fee.',
      'Seats are allotted through merit lists and counselling rounds; select trade and ITI preferences carefully.',
      'Reserved-category seats and women’s and PwD quotas apply as per state rules.',
      'Report to the allotted ITI with originals, pay fees and complete admission before the cut-off date.'],
      [['Process', 'Online application → merit list → counselling → admission']],
      'Many states hold several rounds; keep checking the portal even if you miss your first choice.'),
    P('Trade theory and practical training', 'Year 1', `Learn the fundamentals: ${learn}.`, [
      `Trade practical: ${learn}.`,
      `Tools and equipment you will use: ${tools}.`,
      'Trade theory, workshop calculation and science, engineering drawing and employability skills (communication, entrepreneurship) are taught alongside practicals.',
      safety],
      [['Training', 'Practical-heavy NCVT syllabus'], ['Tools', tools]]),
    P('Advanced training, projects and CITS', 'Year 1–2 (as applicable)', 'Deeper skills and, for two-year trades, advanced practice.', [
      'Two-year trades add advanced trade practicals, projects and more detailed theory in the second year; one-year trades complete these topics in a compressed form.',
      'You may do industrial visits and on-the-job exposure organised by the ITI.',
      'Keep a record of your practicals and projects; assessors check them in the trade test.',
      'ITI instructors and many employers also value the Craft Instructor Training Scheme (CITS) if you later want to teach in an ITI.'],
      [['Optional', 'CITS for instructor career']]),
    P('All India Trade Test and NCVT certificate', 'End of the course', 'AITT is the national exam that gives the National Trade Certificate (NTC).', [
      'The All India Trade Test (AITT) is conducted by the Directorate General of Training (DGT) under NCVT, covering trade theory, trade practical, workshop calculation and science, engineering drawing and employability skills.',
      'Passing it gives you the National Trade Certificate (NTC), which is recognised across India.',
      'Keep your NTC, marksheets and trainee registration number safe; employers and apprenticeship portals ask for them.',
      'Many states also run internal assessments; follow your ITI’s timetable for exam forms.'],
      [['Exam', 'AITT (NCVT)'], ['Certificate', 'National Trade Certificate (NTC)']]),
    P('Apprenticeship and job entry', 'After AITT', apprentice, [
      'After ITI you can register on the Apprenticeship India portal and apply to companies for a one-year apprenticeship under the Apprentices Act; you earn a stipend while training.',
      'Completing an apprenticeship gives the National Apprenticeship Certificate (NAC), which improves job prospects and is accepted for many government recruitments.',
      `Typical jobs: ${jobs}.`,
      selfEmp],
      [['Programme', 'Apprenticeship India / NAPS'], ['Certificate', 'NAC']]),
    P('Licensing, upgrading and government jobs', 'After ITI', 'Add a licence, a diploma or government recruitment to grow.', [
      licence,
      upgrade,
      'Government and PSU recruitment: Indian Railways (RRB Technician, Group D and ALP posts), defence establishments, PSUs and state departments regularly recruit ITI holders for relevant trades.',
      'Short upskilling courses under Skill India and employer training improve your pay and role.'],
      [['Recruiters', 'Railways, PSUs, defence, state departments'], ['Upgrade', 'Diploma lateral entry (2nd year)']]),
  ], [src.dgt, src.naps, src.skill]);

export default [
iti({ slug: 'iti-electrician', name: 'ITI Electrician', title: 'ITI Electrician', dur: '2 years', elig: 'Class 10 pass with Science and Maths',
  learn: 'domestic and industrial wiring, earthing, testing of circuits, transformers, motors, generators, control panels and basic maintenance', tools: 'multimeter, megger, tester, wire strippers, drills, conduit and cable tools', safety: 'Electrical safety, correct earthing, use of insulated tools and isolation procedures are taught from day one; follow them strictly.',
  apprentice: 'Electrician is one of the most in-demand apprenticeship trades in factories, utilities and construction.', jobs: 'electrician, maintenance technician, panel wiring technician, lineman assistant and substation attendant', selfEmp: 'Self-employment: electrical repair and wiring services, subject to local licensing for contractors.',
  licence: 'To undertake electrical contracting or work as a licensed wireman or supervisor, apply for the licence or competency certificate issued by your state’s Electrical Licensing Board; rules and exams vary by state.', upgrade: 'Upgrade: diploma in electrical engineering through lateral entry into the second year after ITI in many states.' }),
iti({ slug: 'iti-wireman', name: 'ITI Wireman', title: 'ITI Wireman', dur: '~1 year', elig: 'Class 10 pass (check the state rule)',
  learn: 'wiring of houses and buildings, conduit and cable laying, earthing, switchgear, meters, and testing and fault finding', tools: 'wire strippers, pliers, testers, multimeter, drills and cable tools', safety: 'Learn safe isolation, earthing and protective devices; electrical accidents are preventable with the right procedure.',
  apprentice: 'Wireman apprentices are taken by electrical contractors, building firms and distribution companies.', jobs: 'wireman, electrical helper, panel assembler and maintenance assistant', selfEmp: 'Self-employment: house wiring and repair work, subject to local electrical licensing rules.',
  licence: 'A wireman or contractor licence from your state’s Electrical Licensing Board is needed for independent electrical contracting; check the exam and experience requirements in your state.', upgrade: 'Upgrade: join the ITI Electrician trade or a diploma through lateral entry, where eligible.' }),
iti({ slug: 'iti-fitter', name: 'ITI Fitter', title: 'ITI Fitter', dur: '2 years', elig: 'Class 10 pass',
  learn: 'filing, marking, cutting, drilling, tapping, threading, fitting and assembling of machine parts, and use of precision measuring instruments', tools: 'vernier calipers, micrometers, hacksaws, files, drills, taps and dies, and bench vices', safety: 'Workshop safety, safe use of hand and power tools and personal protective equipment are core to every practical.',
  apprentice: 'Fitter is a top apprenticeship trade in engineering, automobile, railway and heavy-industry units.', jobs: 'fitter, assembly technician, maintenance fitter, machine operator and tool room assistant', selfEmp: 'Self-employment: fabrication and repair workshops and small engineering units.',
  licence: 'No state licence is needed for most fitter roles; employers look for the NTC and apprenticeship record, and some industries ask for welding or safety certificates.', upgrade: 'Upgrade: diploma in mechanical or production engineering through lateral entry, or advanced CNC and CAD training.' }),
iti({ slug: 'iti-machinist', name: 'ITI Machinist', title: 'ITI Machinist', dur: '2 years', elig: 'Class 10 pass',
  learn: 'operation of lathe, milling, shaping, drilling and grinding machines, reading engineering drawings and producing components to tolerance', tools: 'lathe, milling and grinding machines, cutting tools, micrometers and gauges', safety: 'Machine guarding, correct clamping, chip handling and eye and hand protection are essential in machine shops.',
  apprentice: 'Machinists are hired as apprentices by manufacturing, automotive component and tool room units.', jobs: 'machinist, CNC operator (after upskilling), tool room operator and quality inspector', selfEmp: 'Self-employment: small machine shops and job-work units.',
  licence: 'There is no separate licence, but CNC programming and metrology certificates raise your pay.', upgrade: 'Upgrade: CNC/CAD-CAM training, a diploma in production or mechanical engineering through lateral entry, or CITS.' }),
iti({ slug: 'iti-turner', name: 'ITI Turner', title: 'ITI Turner', dur: '2 years', elig: 'Class 10 pass',
  learn: 'lathe operation, turning, facing, threading, taper turning, boring and producing cylindrical components to size', tools: 'centre lathe, cutting tools, chucks, micrometers, vernier calipers and gauges', safety: 'Lathe safety, correct tool setting, chip control and protective equipment are practised throughout.',
  apprentice: 'Turner apprentices are placed in machine shops, auto-parts makers and railway workshops.', jobs: 'turner, lathe operator, tool room assistant and CNC turning operator (after upskilling)', selfEmp: 'Self-employment: turning and job-work shops.',
  licence: 'No state licence is required, but precision measurement and CNC turning certificates are valued.', upgrade: 'Upgrade: CNC turning training, a diploma in mechanical/production engineering via lateral entry, or CITS.' }),
iti({ slug: 'iti-welder', name: 'ITI Welder', title: 'ITI Welder', dur: '~1 year', elig: 'Class 8 pass (check the state rule)',
  learn: 'gas welding, arc welding, MIG/TIG basics, cutting, joint preparation, reading welding symbols and weld inspection', tools: 'arc welding set, gas welding set, MIG/TIG equipment, chipping hammers, grinders and protective gear', safety: 'Eye, skin and fume protection, fire safety and safe cylinder handling are essential for every welding exercise.',
  apprentice: 'Welding apprentices are in demand in fabrication, shipbuilding, construction and pipeline companies.', jobs: 'welder, fabricator, pipe welder, structural welder and welding inspector assistant', selfEmp: 'Self-employment: fabrication, grill and gate work and repair shops.',
  licence: 'For pressure vessel, pipeline and boiler work, welders take qualification tests such as a welder performance qualification to codes like ASME or IBR; employers arrange these.', upgrade: 'Upgrade: certified welding inspector training or a diploma in mechanical or production engineering through lateral entry.' }),
iti({ slug: 'iti-plumber', name: 'ITI Plumber', title: 'ITI Plumber', dur: '~1 year', elig: 'Class 8 pass (check the state rule)',
  learn: 'pipe cutting, threading and joining, installation of water supply, drainage and sanitary fittings, and reading plumbing drawings', tools: 'pipe wrenches, pipe cutters, threading dies, hacksaws, pipe benders and measuring tools', safety: 'Safe handling of tools, hot works and sanitary hygiene are covered along with trench and site safety.',
  apprentice: 'Plumber apprentices work with construction firms, facility management companies and housing projects.', jobs: 'plumber, pipe fitter, maintenance plumber and sanitary installer', selfEmp: 'Self-employment: plumbing contracting and repair services.',
  licence: 'Some municipalities require a licensed plumber for certain building work; check your local body’s rules.', upgrade: 'Upgrade: diploma in civil engineering through lateral entry, or advanced pipe-fitting and fire-fighting system training.' }),
iti({ slug: 'iti-refrigeration-ac', name: 'ITI Refrigeration & AC', title: 'ITI Refrigeration and Air Conditioning Technician', dur: '1–2 years', elig: 'Class 10 pass',
  learn: 'refrigeration cycles, compressors, condensers, evaporators, installation and servicing of ACs and refrigerators, gas charging and fault finding', tools: 'manifold gauge set, vacuum pump, leak detectors, brazing kit, tube cutters and multimeter', safety: 'Learn safe handling of refrigerant gases, brazing safety and electrical safety.',
  apprentice: 'RAC apprentices are taken by AC manufacturers, service companies and facility maintenance firms.', jobs: 'AC technician, refrigeration mechanic, cold storage technician and HVAC service technician', selfEmp: 'Self-employment: AC and refrigerator service and installation business.',
  licence: 'Technicians handling refrigerants are expected to follow environmental rules; manufacturer certifications add value.', upgrade: 'Upgrade: HVAC courses, diploma in mechanical engineering through lateral entry, or advanced chiller and VRV training.' }),
iti({ slug: 'iti-mechanic-diesel', name: 'ITI Mechanic Diesel', title: 'ITI Mechanic Diesel', dur: '2 years', elig: 'Class 10 pass',
  learn: 'diesel engine construction, fuel injection systems, cooling, lubrication, overhauling, troubleshooting and servicing of diesel vehicles and generators', tools: 'engine tool kits, fuel injection testers, compression testers, micrometers and diagnostic tools', safety: 'Workshop safety, safe lifting and handling of fuels and oils and fire precautions are practised.',
  apprentice: 'Diesel mechanics are taken as apprentices by transport companies, truck and tractor makers and service centres.', jobs: 'diesel mechanic, heavy vehicle mechanic, generator technician and tractor mechanic', selfEmp: 'Self-employment: truck, tractor and generator repair garages.',
  licence: 'Heavy vehicle driving or inspection roles need a driving licence or authorisation from the Regional Transport Office where applicable.', upgrade: 'Upgrade: diploma in automobile or mechanical engineering through lateral entry, or OEM-specific training.' }),
iti({ slug: 'iti-mechanic-motor-vehicle', name: 'ITI Mechanic Motor Vehicle', title: 'ITI Mechanic Motor Vehicle', dur: '2 years', elig: 'Class 10 pass',
  learn: 'petrol and diesel engines, transmission, brakes, suspension, steering, electrical systems, wheel alignment and servicing of cars and two-wheelers', tools: 'engine tool kits, scan tools, wheel alignment tools, brake testers and multimeters', safety: 'Workshop safety, safe use of vehicle lifts and jacks and handling of fuels and batteries are essential.',
  apprentice: 'MMV apprentices are taken by dealerships, authorised service centres and automobile plants.', jobs: 'automobile mechanic, service technician, dealership technician and body shop assistant', selfEmp: 'Self-employment: garages, two-wheeler and car servicing and EV repair after training.',
  licence: 'A driving licence is useful for test-driving; manufacturer certifications help growth in dealerships.', upgrade: 'Upgrade: diploma in automobile engineering through lateral entry, and short courses in EV and hybrid vehicles.' }),
iti({ slug: 'iti-electronics-mechanic', name: 'ITI Electronics Mechanic', title: 'ITI Electronics Mechanic', dur: '2 years', elig: 'Class 10 pass with Science and Maths',
  learn: 'electronic components, soldering, PCB assembly, power supplies, amplifiers, digital circuits, microcontroller basics and repair of consumer electronics', tools: 'soldering station, multimeter, oscilloscope, function generator and hand tools', safety: 'ESD precautions, safe soldering and electrical safety are part of lab practice.',
  apprentice: 'Electronics mechanics are placed by electronics manufacturers, EMS companies and service centres.', jobs: 'electronics technician, PCB assembler, repair technician, CCTV and telecom technician', selfEmp: 'Self-employment: mobile, TV and appliance repair and CCTV installation.',
  licence: 'No state licence is required for most roles; manufacturer and telecom certificates help.', upgrade: 'Upgrade: diploma in electronics and communication engineering through lateral entry, or embedded and IoT short courses.' }),
iti({ slug: 'iti-instrument-mechanic', name: 'ITI Instrument Mechanic', title: 'ITI Instrument Mechanic', dur: '2 years', elig: 'Class 10 pass with Science and Maths',
  learn: 'pressure, temperature, flow and level instruments, calibration, pneumatic and electronic control loops, PLC basics and troubleshooting', tools: 'calibrators, pressure gauges, multimeters, loop testers and hand tools', safety: 'Plant safety, hazardous area precautions and lock-out/tag-out procedures are taught.',
  apprentice: 'Instrument mechanics are taken by refineries, power plants, chemical and pharma plants and automation companies.', jobs: 'instrument mechanic, instrumentation technician, calibration technician and control room assistant', selfEmp: 'Self-employment: calibration and maintenance services for local industries.',
  licence: 'Industrial plants require site safety training and permits to work; vendor certificates add value.', upgrade: 'Upgrade: diploma in instrumentation or electronics through lateral entry, or PLC/SCADA courses.' }),
iti({ slug: 'iti-copa', name: 'ITI COPA', title: 'ITI COPA (Computer Operator and Programming Assistant)', dur: '1 year', elig: 'Class 10 pass',
  learn: 'computer fundamentals, MS Office, internet and email, DTP, programming basics in languages such as C or Python, database basics and web design', tools: 'desktop computers, MS Office, browsers, programming editors and printers', safety: 'Learn data safety, cyber safety, ergonomic practices and proper electrical handling of equipment.',
  apprentice: 'COPA apprentices are taken by government offices, banks, schools and private companies for data entry and office support.', jobs: 'computer operator, data entry operator, office assistant, DTP operator and junior programmer assistant', selfEmp: 'Self-employment: cyber cafe, typing and DTP, and online application services.',
  licence: 'Government clerical and data entry recruitments may ask for typing speed and computer certificates such as CCC or O-Level.', upgrade: 'Upgrade: BCA, a diploma in computer engineering through lateral entry, or short courses in web development and accounting software.' }),
iti({ slug: 'iti-draughtsman-civil', name: 'ITI Draughtsman Civil', title: 'ITI Draughtsman Civil', dur: '2 years', elig: 'Class 10 pass with Science and Maths',
  learn: 'engineering drawing, building plans, elevations and sections, structural details, estimation and CAD drafting', tools: 'drawing instruments, drawing sheets, AutoCAD and scale rulers', safety: 'Site visits require basic safety gear; the trade teaches clean, accurate and standard drawing practice.',
  apprentice: 'Draughtsman apprentices are placed with architects, civil contractors, PWD offices and consultancies.', jobs: 'civil draughtsman, CAD operator, estimator assistant and surveyor’s assistant', selfEmp: 'Self-employment: drafting and plan-making services for builders and homeowners.',
  licence: 'Plans submitted to local bodies must be signed by a registered architect or engineer; draughtsmen prepare drawings under supervision.', upgrade: 'Upgrade: diploma in civil engineering through lateral entry, and advanced AutoCAD and Revit training.' }),
iti({ slug: 'iti-surveyor', name: 'ITI Surveyor', title: 'ITI Surveyor', dur: '~1 year', elig: 'Class 10 pass with Maths',
  learn: 'chain and compass surveying, levelling, theodolite and total station use, plotting maps and contour plans, and reading survey drawings', tools: 'levels, theodolites, total stations, chains, tapes, ranging rods and survey software', safety: 'Field safety on roads and construction sites, proper use of instruments and weather precautions are taught.',
  apprentice: 'Surveyor apprentices are taken by civil contractors, PWD, irrigation departments and survey agencies.', jobs: 'surveyor, survey assistant, levelling assistant and site setup technician', selfEmp: 'Self-employment: land measurement and plot survey services where permitted.',
  licence: 'Government land survey roles may require specific state licences or exams; check your state revenue department’s rules.', upgrade: 'Upgrade: diploma in civil engineering through lateral entry, and total station and GPS/GIS short courses.' }),
iti({ slug: 'iti-beauty-culture', name: 'ITI Beauty Culture', title: 'ITI Beauty Culture and Hair', dur: '~1 year', elig: 'Class 10 pass (check the state rule)',
  learn: 'skin, hair and nail care, hair cutting and styling, facials, makeup, hygiene and salon practices', tools: 'hair cutting and styling tools, makeup kits, steamer, facial equipment and sterilisers', safety: 'Hygiene, sterilisation of tools, safe use of chemicals and skin-test routines are core parts of the course.',
  apprentice: 'Beauty apprentices are placed in salons, spas and beauty brands for practice and stipend.', jobs: 'beautician, hair stylist, makeup artist, spa therapist and salon assistant', selfEmp: 'Self-employment: salon, home-based services and bridal makeup; training in entrepreneurship is part of the course.',
  licence: 'Some cities require a trade or health licence for salons; check local municipal rules.', upgrade: 'Upgrade: advanced courses in cosmetology, makeup artistry or salon management.' }),
iti({ slug: 'iti-sewing-technology', name: 'ITI Sewing Technology', title: 'ITI Sewing Technology', dur: '~1 year', elig: 'Class 8 pass (check the state rule)',
  learn: 'machine sewing, cutting, pattern making, garment construction, finishing and quality checking of ladies and gents garments', tools: 'sewing machines, scissors, measuring tapes, pattern paper and irons', safety: 'Safe operation of sewing machines and irons, ergonomic posture and workplace hygiene are taught.',
  apprentice: 'Sewing technology apprentices are placed in garment factories, boutiques and export units.', jobs: 'tailor, garment machine operator, pattern maker and quality checker', selfEmp: 'Self-employment: tailoring and boutique business, often home-based.',
  licence: 'No licence is normally needed; registration under local shop and establishment rules applies to a business.', upgrade: 'Upgrade: diploma in fashion design or apparel technology.' }),
];
